### PR TITLE
Add Google Analytics

### PR DESCRIPTION
**Pull request by ctlnwng**
Installed `gatsby-plugin-google-analytics` to hook up the site to Google Analytics! The analytics dashboard is under the `tech@hackbeanpot.com` account!

https://www.gatsbyjs.org/docs/adding-analytics/

We won't be able to see if it is properly tracking until the site is live, but it should be all set up!

### CODE REVIEW

**Comment by ctlnwng** [comment]
UGH I can’t use that plugin without upgrading to Gatsby 2.0….which might affect a bunch of other things....hold on...

**Comment by vychun** [comment]
oh big rip :(((

**Comment by ctlnwng** [comment]
@vychun Okay!!! I had to make a bunch of changes to upgrade to Gatsby 2.0 but everything is working now! https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/

**Comment by ctlnwng** [comment]
@vychun 

Remember to `npm install`! If you get errors, try deleting `node_modules` and `package-lock.json` first.

**Pull request merged**
